#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5FEE05E6A56E15A3 (hub@nit.ca)
#
Name     : exempi
Version  : 2.4.5
Release  : 12
URL      : https://libopenraw.freedesktop.org/download/exempi-2.4.5.tar.bz2
Source0  : https://libopenraw.freedesktop.org/download/exempi-2.4.5.tar.bz2
Source99 : https://libopenraw.freedesktop.org/download/exempi-2.4.5.tar.bz2.asc
Summary  : Library for easy parsing of XMP metadata.
Group    : Development/Tools
License  : BSD-3-Clause-Clear
Requires: exempi-bin
Requires: exempi-lib
Requires: exempi-license
Requires: exempi-man
BuildRequires : boost-dev
BuildRequires : expat-dev
BuildRequires : pkgconfig(zlib)
Patch1: cve-2018-12648.patch

%description
exempi is a port of Adobe XMP SDK to work on UNIX and to be build with
GNU automake.

%package bin
Summary: bin components for the exempi package.
Group: Binaries
Requires: exempi-license
Requires: exempi-man

%description bin
bin components for the exempi package.


%package dev
Summary: dev components for the exempi package.
Group: Development
Requires: exempi-lib
Requires: exempi-bin
Provides: exempi-devel

%description dev
dev components for the exempi package.


%package lib
Summary: lib components for the exempi package.
Group: Libraries
Requires: exempi-license

%description lib
lib components for the exempi package.


%package license
Summary: license components for the exempi package.
Group: Default

%description license
license components for the exempi package.


%package man
Summary: man components for the exempi package.
Group: Default

%description man
man components for the exempi package.


%prep
%setup -q -n exempi-2.4.5
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534600997
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1534600997
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/exempi
cp COPYING %{buildroot}/usr/share/doc/exempi/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/exempi

%files dev
%defattr(-,root,root,-)
/usr/include/exempi-2.0/exempi/xmp++.hpp
/usr/include/exempi-2.0/exempi/xmp.h
/usr/include/exempi-2.0/exempi/xmpconsts.h
/usr/include/exempi-2.0/exempi/xmperrors.h
/usr/lib64/libexempi.so
/usr/lib64/pkgconfig/exempi-2.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libexempi.so.3
/usr/lib64/libexempi.so.3.4.5

%files license
%defattr(-,root,root,-)
/usr/share/doc/exempi/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/exempi.1
